In [2]:
import numpy as np

In [38]:
x = np.random.rand(100)
y = np.random.rand(100)
w = np.random.rand(100)
x_len = np.sqrt(np.dot(x,x))
x_len

5.882628545277664

In [39]:
x_avg = np.sum(x*w)/np.sum(w)
x_avg

0.5342093842170499

In [40]:
dot_prod = np.dot(x, y)
dot_prod

27.855147803718616

In [41]:
temp = x-y
distance = np.sqrt(np.dot(temp, temp))
distance

3.8603342783345544

In [62]:
X = np.random.rand(100, 1000)
X_len = np.sqrt(np.sum(X ** 2, axis=0))
X_len

array([5.55572984, 5.88196646, 5.94486063, 5.19957273, 5.94061151,
       5.91184764, 5.73914508, 5.83475346, 6.03749986, 6.12508746,
       5.93575845, 5.78442834, 5.38037595, 5.99530396, 5.5548507 ,
       5.53284061, 6.28310037, 5.54838478, 5.36977614, 5.78829858,
       5.43305604, 5.52935331, 5.7442331 , 5.98319514, 5.77699103,
       5.90130577, 5.9399899 , 5.53195511, 5.87527374, 5.78284136,
       5.85026576, 5.90244842, 5.863663  , 5.80052138, 5.72499604,
       5.5951189 , 5.95512808, 5.70948159, 6.13300373, 5.51789905,
       5.87766807, 5.87584394, 5.65882466, 5.81914518, 5.89946497,
       5.72531726, 6.5510416 , 5.45366445, 5.88024808, 6.25260292,
       5.50844464, 5.93115656, 6.02716652, 5.48494232, 5.1672801 ,
       5.47564197, 5.83783947, 5.76829403, 5.4865472 , 5.39841645,
       5.78045757, 5.68455902, 5.36897659, 6.03678614, 5.81410921,
       5.96309312, 6.11812853, 5.76918697, 6.10187468, 6.19815698,
       5.917851  , 6.14618503, 6.22885786, 6.07061885, 6.13168

In [64]:
X_avg = np.sum(X.T*w, axis=1)/np.sum(w)
X_avg

array([0.44967349, 0.50171641, 0.4922917 , 0.40376772, 0.53274461,
       0.49008175, 0.466232  , 0.50079686, 0.54281494, 0.5189766 ,
       0.50213543, 0.51201166, 0.45855265, 0.53180506, 0.45743379,
       0.44474841, 0.56513697, 0.45615914, 0.46167064, 0.49903741,
       0.48019017, 0.47849857, 0.52337283, 0.51613781, 0.52807458,
       0.54710445, 0.54203301, 0.47809362, 0.50050476, 0.50151343,
       0.5198411 , 0.52278944, 0.50239947, 0.51161002, 0.51175142,
       0.480578  , 0.52720048, 0.51722619, 0.54593746, 0.45623561,
       0.50759584, 0.53949155, 0.50305334, 0.53118113, 0.51112419,
       0.49192273, 0.61378866, 0.46738001, 0.521376  , 0.55721434,
       0.47516158, 0.53014682, 0.51531186, 0.46796947, 0.44310396,
       0.48511537, 0.51634434, 0.50608862, 0.48484326, 0.45715961,
       0.49759651, 0.50842478, 0.46669504, 0.53738782, 0.51796668,
       0.52564249, 0.52748406, 0.4754847 , 0.51499199, 0.53878236,
       0.53013643, 0.51639409, 0.52294356, 0.53277603, 0.55632

In [60]:
X_dist = np.sqrt(np.sum(((X.T-y) ** 2), axis=1))
X_dist

array([4.3292673 , 4.57373367, 4.04220288, 4.2153584 , 4.2383398 ,
       4.05910065, 4.17863668, 3.82258118, 4.01390944, 3.99517964,
       3.7663301 , 4.41228113, 4.2110807 , 3.55289685, 3.90051233,
       4.47929561, 4.40952274, 4.2716562 , 4.15767564, 4.13148178,
       4.25713146, 4.11137567, 3.7934041 , 4.04824321, 3.99178509,
       4.36141521, 4.36287351, 3.99568681, 4.29728236, 3.94968846,
       3.84257188, 3.90336789, 3.9536041 , 4.36470834, 3.99171587,
       4.07319225, 4.03599063, 4.10415621, 4.20558456, 3.84439317,
       4.39293993, 4.26762837, 3.87184272, 3.9862624 , 4.39678988,
       3.9676623 , 3.89423495, 4.25595239, 4.12375948, 4.02117461,
       3.88824901, 4.27528279, 3.85539321, 4.46180898, 3.74847131,
       3.83335555, 4.39447452, 4.06080956, 3.95287589, 3.95451745,
       4.08123085, 4.18252956, 3.76566327, 3.75197694, 4.13575996,
       3.99041966, 4.15522459, 4.1466523 , 4.04019591, 4.27512141,
       4.41908039, 4.01450883, 3.79178162, 3.79476669, 4.18031

In [67]:
X_dot = np.dot(X.T, y)
X_dot

array([25.9387254 , 26.644988  , 25.82780679, 23.45081569, 28.05519971,
       25.86556729, 25.87795537, 25.95417253, 29.37322799, 26.19817676,
       26.90507111, 25.52755072, 25.26873167, 27.69734131, 24.87008715,
       24.1611983 , 27.99818109, 24.09473794, 24.87150043, 25.95659458,
       25.0677758 , 26.25514533, 26.63929152, 26.73553243, 27.58411755,
       26.49599508, 27.60738123, 26.03474228, 26.50105496, 25.03119084,
       25.96842933, 26.77699001, 27.59366464, 25.98492253, 25.54920982,
       25.70824344, 26.76567744, 26.14856833, 27.89306481, 25.03428623,
       25.52663613, 27.43206378, 23.98925045, 26.07850932, 25.48210009,
       25.95195916, 30.74802869, 22.59103961, 27.29529678, 30.05786375,
       24.73046923, 27.35876651, 27.61363703, 25.04929081, 23.39057408,
       23.84375334, 28.83702936, 27.09684061, 24.89810357, 23.44011692,
       25.1884014 , 26.87900915, 24.21525624, 30.10277659, 26.18223278,
       27.58451579, 28.29783751, 25.47692837, 28.82102501, 28.41